base_url = "https://joshuahayes.net"

title = "Joshua Hayes"
description = "Personal website of Joshua Hayes"
default_language = "en"
generate_feeds = true
compile_sass = true
build_search_index = false

# The default author for pages
author = "Joshua Hayes"

# theme = ""

taxonomies = [
  {name = "categories", feed = true},
  {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"
# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => ğŸ˜„)
render_emoji = true
# Whether smart punctuation is enabled (changing quotes, dashes, dots in their typographic form)
# For example, `...` into `â€¦`, `"quote"` into `â€œcurlyâ€` etc
smart_punctuation = true

[extra]
# author = "Joshua Hayes"

even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/about", name = "About"},
]

even_title = "Joshua Hayes"

katex_enable = true
katex_auto_render = true
